apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: conf
data:
  htpasswd: |
    alogo:$apr1$pbMniSeq$m4PZevv7VLULQLhiD2V2R0
    conf_user:$apr1$sDBv9ugd$AV7m5Jeg0463jXaBxiZDs.
    articonf_ui:$apr1$qFaau5L2$xgO53tciXFlrL/Z61nrzP.
    
  mysqld.cnf: |
    [mysqld]
    pid-file	= /var/run/mysqld/mysqld.pid
    socket		= /var/run/mysqld/mysqld.sock
    datadir		= /var/lib/mysql
    #log-error	= /var/log/mysql/error.log
    # By default we only accept connections from localhost
    #bind-address	= 127.0.0.1
    # Disabling symbolic-links is recommended to prevent assorted security risks
    symbolic-links=0

    max_connections = 2048

    
