apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: manager
  name: manager
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30000
  selector:
    io.kompose.service: manager
status:
  loadBalancer: {}
