apiVersion: v1
kind: Service
metadata:
  namespace: conf
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  type: NodePort  
  ports:
  - port: 443
    nodePort: 30001
    protocol: TCP
    name: https
  - port: 80
    protocol: TCP
    name: http    
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {} 
