apiVersion: v1
kind: Service
metadata:
  namespace: conf
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: sure-tosca
  name: sure-tosca
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    io.kompose.service: sure-tosca
status:
  loadBalancer: {}  
